name: Pull Request CI
on: push
env:
  CI: true
  NEXT_TELEMETRY_DISABLED: 1
jobs:
  check-eslint:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: npm Clean install
        run: npm install
      - name: npm Run lint
        run: npm run lint
  build:
    runs-on: ubuntu-22.04
    needs:
      - check-eslint
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: npm Clean install
        run: npm install
      - name: npm Run build
        run: npm run build
  check-test:
    runs-on: ubuntu-22.04
    needs:
      - build
    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Shallow clones should be disabled for a better relevancy of analysis
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "npm"
      - name: npm Clean install
        run: npm install
      - name: npm Run test
        run: npm run test
